# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
# security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#       in_memory:
#            memory: ~

 #   firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
 #       dev:
 #           pattern: ^/(_(profiler|wdt)|css|images|js)/
 #           security: false

 #       main:
 #           anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        admin:
            pattern:   /admin/(.*)
            form_login:
                provider:   fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /admin
                check_path: /admin/login_check
                always_use_default_target_path: true
                default_target_path: /admin
            logout:
                path:   /admin/logout
                target: /admin
            logout:    true
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # login success redirecting options
                always_use_default_target_path: true
                default_target_path: /profile/
                target_path_parameter: _target_path
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }